<?php require 'templates/header.phtml'; ?>

<form class="form" action="addProduct" method="POST">
<div class="">  
        <label>Nombre del producto: </label><input required type="text" name="name">
</div>
<div class="">  
        <label>Categoría: </label>
        <select name="category" required>
                <?php foreach($categories as $category):?>
                <option value='<?=$category->category_id?>'><?=$category->category_name?></option>
                <?php endforeach ?>
        </select>
</div>
<div class="">  
        <label>Precio: </label><input required type="double" name="price">
</div>
<div class="">  
        <label>Cantidad disponible: </label><input required type="number" name="quantity">
</div>
 <button type="submit"> Añadir producto </button>
</form>

<a href='./productsList'>Volver</a>

<?php require 'templates/footer.phtml'; ?>