<?php require "templates/header.phtml" ?>

<h1>Organia tu mercado saludable favorito</h1>
<h2>Acá encontraras los productos de mejor calidad en la ciudad</h2>
<img src= "img/supermercado.jpeg" alt="supermercado">


<div>
<button><a href='./categories'>Ver categorías</a></button>
</div>

<div>
<button><a href='./productsList'>Ver Productos</a></button>
</div>

<div>
<button><a href='./login'>Panel de Administrador</a></button>
</div>

<?php require "templates/footer.phtml" ?>