<?php require_once "templates/header.phtml" ?>

<form action='updateProduct/<?=$id?>' method='POST'>
    <div>
        <label>Nuevo nombre del producto: </label>
        <input name='name' type='text' value='name' required>
    </div>
    <div>
        <label>Categoría a la que pertenece el producto: </label>
        <select name="category" required>
                <?php foreach($categories as $category):?>
                <option value='<?=$category->category_id?>'><?=$category->category_name?></option>
                <?php endforeach ?>
        </select>
    </div>
    <div>
        <label>Precio: </label>
        <input name='price' type='double' value='price' required>
    </div>
    <div>
        <label>Cantidad: </label>
        <input name='quantity' type='number' value='quantity' required>
    </div>

    <button type='submit'>Editar producto</button>
</form>

<a href='./productsList'>Volver</a>

<?php require_once "templates/footer.phtml" ?>