<?php require 'templates/header.phtml' ?>

<div>
    <h1>Lista de categorias: </h1>
    <ul>
        <?php foreach($categories as $category): ?>
            <li><?=$category->category_name?><div><button><a href="category/<?= $category->category_id ?>">Ver categoría</a></button><button><a href="editar-cat/<?= $category->category_id ?>">Editar</a></button><button><a href="delete-category/<?=$category->category_id?>">Eliminar</a></button></div></li>
        <?php endforeach ?>
    </ul>
</div>
<button><a href='enter-category'>Agregar nueva categoría</a></button>

<?php require 'templates/footer.phtml' ?>