<?php require 'templates/header.phtml'; ?>

<form class="form" action="" method="POST"> //que va en el action??
<div class="">  
        <label>Nombre del producto: </label><input required type="text" name="name">
</div>
<div class="">  
        <label>Categoría: </label><input required type="text" name=""> //tiene que ser select
</div>
<div class="">  
        <label>Precio: </label><input required type="text" name="product_ name">
</div>
<div class="">  
        <label>Cantidad disponible: </label><input required type="text" name="product_quantity">
</div>
 <button type="submit"> Añadir producto </button>
</form>

<?php require 'templates/footer.phtml'; ?>