<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <base href="<?= BASE_URL ?>">
    <link rel="stylesheet" href="css/organia.css">
    <title>Organia</title>
</head>
<header>
    <img id="logo" src="img/organialogo.png" alt="organialogo">
</header>

<nav>
    <a href="<?=BASE_URL?>home">Home</a></li>
</nav>

<body>
 <main>