<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <base href="'.BASE_URL.'">
    <title>Organia</title>
</head>
<header>
    <img id="logo" source= "img/organialogo.png" alt="organialogo">
</header>

<nav>
    <a href="<?=BASE_URL?>productsList">Home</a></li> Home
</nav>

<body>
 <main>