
<?php require 'templates/header.phtml'; ?>

<h2>Login</h2>

<form id= "form" action="loginUser" method="POST">
   <input type="text" name="user" placeholder="Usuario" required>
   <input type="password" name="password" placeholder="Contraseña" required>

   <button type="submit"> Ingresar </button>
</form>
<!-- <script src="js/login.js"></script>  -->

<?php require 'templates/footer.phtml'; ?>