<?php require 'templates/header.phtml'; ?>

<button type="submit"> Administrar productos </button>  <a href="<?=BASE_URL?>productsList">Home</a></li> Home
<button type="submit"> Administrar categorías </button> <a href="<?=BASE_URL?>categoriesList">Home</a></li> Home

<button type="submit"> Administrar categorías </button> <a href="<?=BASE_URL?>categoriesList">Home</a></li>  LOGOUT

<?php require 'templates/footer.phtml'; ?>