<?php require 'templates/header.phtml'; ?>

<h3>Detalle del producto:</h2>
    <ul>
        <?php foreach($products as $product): ?>
        <li>Nombre: <?= $product->product_name?></li>
        <li>Categoría: <?= $product->category_name?></li>
        <li>Cantidad: <?= $product->product_stock?></li>
        <li>Precio: <?= $product->product_price?></li>
        <?php endforeach ?>
    </ul>
<a href='./productsList'>Volver</a>
<?php require 'templates/footer.phtml'; ?>