<?php require 'templates/header.phtml'; ?>

    <h1>Organia tu mercado saludable favorito</h1>
    <h2>Acá encontraras los productos de mejor calidad en la ciudad</h2>
    <img source= "img/supermercado.jpeg" alt="supermercado">
  
    <h3>Lista de productos</h2>
    <div>
        <ul>
            <?php foreach($products as $product): ?>
            <li> 
                 <div>
                     <h3><?= $product->product_name?></h5>
                     <p>Categoría: <?=$product->category_name?> </p>
                     <a href="<?=BASE_URL?>details/<?= $product->id ?>">Ver detalles</a>
                </div>
            </li>
            <?php endforeach ?>
        </ul>
    </div>

<?php require 'templates/footer.phtml'; ?>